=== examachine/pisi/pisi-spec.dtd
<!-- Document Type Declaration file for PISI pspec.xml files -->
<!-- http://www.pardus.org.tr/projeler/pisi/ -->

<!ELEMENT PISI (Source,Package+,History)>

<!-- Source Section -->

<!ELEMENT Source (
	#PCDATA |
	Name |
	Homepage |
	Icon |
	Packager |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	Archive |
	Patches |
	BuildDependencies
)*>

<!ELEMENT Name (#PCDATA)>

<!ELEMENT Homepage (#PCDATA)>

<!ELEMENT Icon (#PCDATA)>

<!ELEMENT Packager (Name, Email)>
<!ELEMENT Email (#PCDATA)>

<!ELEMENT License (#PCDATA)>

<!ELEMENT IsA (#PCDATA)>

<!ELEMENT PartOf (#PCDATA)>

<!ELEMENT Summary (#PCDATA)>
<!ATTLIST Summary xml:lang CDATA #IMPLIED>

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description xml:lang CDATA #IMPLIED>

<!ELEMENT Archive (#PCDATA)>
<!ATTLIST Archive sha1sum CDATA #REQUIRED>
<!-- NOTE: we can limit possible types here to the ones that pisi know -->
<!ATTLIST Archive type CDATA #REQUIRED>

<!ELEMENT BuildDependencies (Dependency*)>

<!ELEMENT Dependency (#PCDATA)>
<!ATTLIST Dependency versionFrom CDATA #IMPLIED>
<!ATTLIST Dependency versionTo CDATA #IMPLIED>
<!ATTLIST Dependency version CDATA #IMPLIED>
<!ATTLIST Dependency releaseFrom CDATA #IMPLIED>
<!ATTLIST Dependency releaseTo CDATA #IMPLIED>
<!ATTLIST Dependency release CDATA #IMPLIED>

<!ELEMENT Patches (Patch*)>

<!ELEMENT Patch (#PCDATA)>
<!ATTLIST Patch compressionType CDATA #IMPLIED>
<!ATTLIST Patch level CDATA #IMPLIED>
<!ATTLIST Patch target CDATA #IMPLIED>


<!-- Package Section -->

<!ELEMENT Package (
	#PCDATA |
	Name |
	License |
	IsA |
	PartOf |
	Summary |
	Description |
	RuntimeDependencies |
	Files |
	Conflicts |
	AdditionalFiles |
	Provides
)*>

<!ELEMENT Provides (COMAR)+>
<!ELEMENT COMAR (#PCDATA)>
<!ATTLIST COMAR script CDATA #IMPLIED>

<!ELEMENT Conflicts (Package)+>
<!-- we have a problem here, this Package tag only contains a package name
while dtd treats this as another Package section, who said dtd doesnt
suck anyway -->

<!ELEMENT AdditionalFiles (AdditionalFile+)>
<!ELEMENT AdditionalFile (#PCDATA)>
<!ATTLIST AdditionalFile target CDATA #REQUIRED>
<!ATTLIST AdditionalFile permission CDATA #IMPLIED>
<!ATTLIST AdditionalFile owner CDATA #IMPLIED>

<!ELEMENT RuntimeDependencies (Dependency*)>

<!ELEMENT Files (Path)+>

<!ELEMENT Path (#PCDATA)>
<!-- NOTE: is this list correct? -->
<!ATTLIST Path fileType
	(executable|library|data|config|doc|man|info|localedata|header)
	#REQUIRED>
<!ATTLIST Path permanent (false|true) #IMPLIED>


<!-- History Section -->

<!ELEMENT History (Update+)>

<!ELEMENT Update (#PCDATA | Date | Version | Comment | Name | Email)*>
<!ATTLIST Update release CDATA #REQUIRED>
<!-- FIXME: valid types must be used instead of CDATA -->
<!ATTLIST Update type CDATA #IMPLIED>

<!ELEMENT Date (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT Comment (#PCDATA)>

=== examachine/pisi/tests/buildtests/merhaba-pisi-1.0/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.uludag.org.tr/projeler/pisi/pisi-spec.dtd">

<PISI>
    <Source>
        <Name>a</Name>
        <Homepage>http://wiki.pisilinux.org/tr/index.php?title=PiSi_Hello_World</Homepage>
        <Packager>
            <Name>A. Murat Eren</Name>
            <Email>meren@uludag.org.tr</Email>
        </Packager>
        <License>As-Is</License>
        <PartOf>None</PartOf>
        <IsA>app:console</IsA>
        <Summary>PiSi Hello World Application..</Summary>
        <Summary xml:lang="tr">PiSi için merhaba dünya uygulaması, süper bir konsol uygulaması</Summary>
        <Description>Just a basic application. Nothing to describe.</Description>
        <Description xml:lang="tr">Sadece basit bir uygulama, açıklayacak bir şey yok</Description>
        <Archive sha1sum="fc917dec7b9729de935698f273f8007b2223653d" type="targz">http://cekirdek.uludag.org.tr/~meren/merhaba-pisi-1.0.tar.gz</Archive>
    </Source>

    <Package>
        <Name>a</Name>
        <Files>
            <Path fileType="executable">/usr/bin/</Path>
        </Files>
    </Package>


    <History>
        <Update release="1">
            <Date>2006-02-01</Date>
            <Version>1.0</Version>
            <Comment>First release.</Comment>
            <Name>A. Murat Eren</Name>
            <Email>meren@uludag.org.tr</Email>
        </Update>
    </History>
</PISI>

=== examachine/pisi/tests/unzip2/pspec.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE PISI SYSTEM "http://www.uludag.org.tr/projeler/pisi/pisi-spec.dtd">

<PISI>
    <Source>
        <Name>unzip</Name>
        <Homepage>ftp://ftp.info-zip.org/pub/infozip/UnZip.html</Homepage>
        <Packager>
            <Name>A. Murat Eren</Name>
            <Email>meren@uludag.org.tr</Email>
        </Packager>
        <License>Info-ZIP</License>
        <IsA>category</IsA>
        <PartOf>component</PartOf>
        <Summary xml:lang="en">Unzipper for pkzip-compressed files</Summary>
        <Description xml:lang="en">Unzipper for pkzip-compressed files</Description>
        <Archive type="targz" sha1sum="abf7de8a4018a983590ed6f5cbd990d4740f8a22">http://pkgs.fedoraproject.org/repo/pkgs/unzip/unzip60.tar.gz/62b490407489521db863b523a7f86375/unzip60.tar.gz</Archive>
        <Patches>
		   <!-- <Patch level="1">unzip-5.50-dotdot.patch</Patch> -->
         </Patches>
        <BuildDependencies>
            <Dependency>libc</Dependency>
            <Dependency>sed</Dependency>
            <Dependency>patch</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>unzip</Name>
        <RuntimeDependencies>
            <!-- <Dependency>libc</Dependency> -->
        </RuntimeDependencies>
        <Files>
    	    <Path fileType="binary">/usr/bin</Path>
    	    <Path fileType="doc">/usr/share/doc</Path>
    	    <Path fileType="doc">/usr/share/man</Path>
        </Files>
  </Package>
  <History>
     <Update release="2">
        <Date>2009-11-19</Date>
        <Version>6.0</Version>
     </Update>
    <Update release="2">
      <Date>2005-08-10</Date>
      <Version>5.52</Version>
    </Update>
 </History>

</PISI>

=== examachine/pisi/tests/popt/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.pardus.org.tr/projeler/pisi/pisi-spec.dtd">
<PISI>
    <Source>
        <Name>popt</Name>
        <Homepage>http://www.rpm.org/</Homepage>
        <Packager>
            <Name>Kırmızı kafalar</Name>
            <Email>hotmail@redhat.com</Email>
        </Packager>
        <License>as-is</License>
        <IsA>app:console</IsA>
        <PartOf>system.base</PartOf>
        <Summary>Popt command line option parser</Summary>
        <Description>Command line option parsing library.
        While it is similiar to getopt(3), it contains a number of enhancements, including:

        1) popt is fully reentrant
        2) popt can parse arbitrary argv[] style arrays while 
            getopt(2) makes this quite difficult
        3) popt allows users to alias command line arguments
        4) popt provides convience functions for parsing strings
            into argv[] style arrays
        </Description>
        <Archive sha1sum="66f3c77b87a160951b180447f4a6dce68ad2f71b" type="targz">ftp://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/vendor/sun/freeware/SOURCES/popt-1.7.tar.gz</Archive>
        <Patches>
          <Patch compressionType="gz" level="1">popt-1.7-uclibc.patch.gz</Patch>
        </Patches>
        <BuildDependencies>
          <Dependency versionFrom="1.8"> make </Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>popt</Name>
        <Description>library files for popt</Description>
        <Summary>Command line option parsing library</Summary>
        <Summary xml:lang="tr">Komut satırı seçenekleri işleme kütüphanesi</Summary>
        <RuntimeDependencies>
            <Dependency>gettext</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="library">/usr/lib</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="man">/usr/share/man</Path>
            <Path fileType="localedata">/usr/share/locale</Path>
            <Path fileType="header">/usr/include/popt.h</Path>
        </Files>
    </Package>

    <Package>
      <Name>popt-libs</Name>
      <Summary xml:lang="en">Command line option parsing library</Summary>
      <Summary xml:lang="tr">Komut satırı seçenekleri işleme kütüphanesi</Summary>
      <RuntimeDependencies>
        <Dependency>gettext</Dependency>
      </RuntimeDependencies>
      <Description>library files for popt</Description>
      <Files>
        <Path fileType="sharedLib">/usr/lib</Path>
        <Path fileType="doc">/usr/share/doc</Path>
        <Path fileType="doc">/usr/share/man</Path>
        <Path fileType="localedata">/usr/share/locale</Path>
        <Path fileType="header">/usr/include/popt.h</Path>
      </Files>
      <AdditionalFiles>
        <AdditionalFile owner="root" permission="0755" target="/etc/init.d/acpid">acpid.rc6</AdditionalFile>
      </AdditionalFiles>
    </Package>

    <History>
        <Update release="1">
            <Date>2005-06-14</Date>
            <Version>1.7</Version>
            <Comment>First release.</Comment>
            <Name>Kırmızı kafalar</Name>
            <Email>hotmail@redhat.com</Email>
        </Update>
    </History>
</PISI>

=== examachine/pisi/tests/zip2/pspec.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE PISI SYSTEM "http://www.uludag.org.tr/projeler/pisi/pisi-spec.dtd">

<PISI>
    <Source>
        <Name>zip</Name>
        <Homepage>ftp://ftp.freesoftware.com/pub/infozip/Zip.html</Homepage>
        <Packager>
            <Name>PACKAGER</Name>
            <Email>PACKAGER_EMAIL</Email>
        </Packager>
        <License>Info-ZIP</License>
        <IsA>category</IsA>
        <PartOf>component</PartOf>
        <Summary xml:lang="en">Info ZIP (encryption support)</Summary>
        <Description xml:lang="en">Info ZIP (encryption support)</Description>
        <Archive type="targz" sha1sum="34ba126eb3344b0a35ee1a00fff9639994c7aba4">http://pkgs.fedoraproject.org/repo/pkgs/zip/zip231.tar.gz/6bfc076664416251d7624ab3538d1cb9/zip231.tar.gz</Archive>
        <Patches>
    		<!--Patch>zip-2.3-unix_configure-pic.patch</Patch> -->
    		<!-- <Patch level="1">zip-CAN-2004-1010.patch</Patch> -->
            <!-- <Patch level="1">zcrypt.patch</Patch> -->
        </Patches>
        <BuildDependencies>
            <Dependency>unzip</Dependency>
            <Dependency>patch</Dependency>
        </BuildDependencies>
    </Source>

    <Package>
        <Name>zip</Name>
        <RuntimeDependencies>
	    <Dependency>unzip</Dependency>
        </RuntimeDependencies>
        <Files>
            <Path fileType="binary">/usr/bin</Path>
            <Path fileType="doc">/usr/share/doc</Path>
            <Path fileType="doc">/usr/share/man</Path>
        </Files>
  </Package>

  <History>
    <Update release="3">
        <Date>2005-11-20</Date>
        <Version>2.31</Version>
    </Update>
     <Update release="2">
       <Date>2005-11-10</Date>
       <Version>2.31</Version>
     </Update>
  </History>

</PISI>

=== examachine/pisi/tests/helloworld/pspec.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE PISI SYSTEM "http://www.uludag.org.tr/projeler/pisi/pisi-spec.dtd">

<PISI>
    <Source>
        <Name>helloworld</Name>
        <Homepage>http://www.uludag.org.tr</Homepage>
        <Packager>
            <Name>S.Çağlar Onur</Name>
            <Email>caglar@uludag.org.tr</Email>
        </Packager>
        <License>GPL-2</License>
        <IsA>category</IsA>
        <PartOf>component</PartOf>
        <Summary xml:lang="en">Dummy HelloWorld for testing ActionsAPI</Summary>
        <Description xml:lang="en">Dummy HelloWorld for testing ActionsAPI</Description>
        <Archive type="tarbz2" sha1sum="3d7ee247c109d28db3437d2ce24f0e16f388d874">https://github.com/examachine/pisi/raw/master/tests/helloworld/helloworld-2.0.tar.bz2</Archive>
    </Source>

    <Package>
        <Name>helloworld</Name>
        <Files>
            <Path fileType="binary">/</Path>
        </Files>
  </Package>

          <History>
            <Update release="1">
                <Date>2005-08-21</Date>
                <Version>0.1</Version>
            </Update>
        </History>
</PISI>

=== examachine/pisi/tests/stress/comp/bc/pspec.xml
<?xml version="1.0" ?>
<!DOCTYPE PISI SYSTEM "http://www.uludag.org.tr/projeler/pisi/pisi-spec.dtd">

<PISI>
    <Source>
        <Name>bc</Name>
        <Homepage>http://www.gnu.org/software/bc/bc.htm</Homepage>
        <Packager>
            <Name>Pardus Testcioğlu</Name>
            <Email>bilgi@uludag.org.tr</Email>
        </Packager>
        <License>GPL-2</License>
        <IsA>category</IsA>
        <Summary>Handy console-based calculator utility</Summary>
        <Summary xml:lang="tr">Şık görünümlü bir konsol temelli hesap makinesı</Summary>
        <Description>Handy console-based calculator utility</Description>
        <Description xml:lang="tr">Konsolda çalışan şık görünümlü bir hesap makinesı</Description>
        <Archive sha1sum="c8f258a7355b40a485007c40865480349c157292" type="targz">ftp://ftp.ulak.net.tr/gnu/gnu/bc/bc-1.06.tar.gz</Archive>
        <BuildDependencies>
            <Dependency>ab</Dependency>
        </BuildDependencies>
        <Patches>
            <Patch level="1">bc-1.06-info-fix.diff</Patch>
            <Patch level="1">bc-1.06-longopts.patch</Patch>
            <Patch level="1">bc-1.06-readline42.diff</Patch>
            <Patch level="1">bc-1.06-static-save.patch</Patch>
        </Patches>
    </Source>

    <Package>
        <Name>bc</Name>
        <RuntimeDependency>
            <Dependency>ab</Dependency>
        </RuntimeDependency>
        <Files>
            <Path fileType="executable">/</Path>
        </Files>
    </Package>

    <History>
        <Update release="1">
            <Date>2005-12-18</Date>
            <Version>1.06</Version>
            <Comment>First release.</Comment>
            <Name>Pardus Testcioğlu</Name>
            <Email>bilgi@uludag.org.tr</Email>
        </Update>
    </History>
</PISI>
